ALTER TABLE `emulator_settings`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `emulator_texts`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_achievements`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `bot_serves`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `calendar_rewards_claimed`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `special_enables`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `trax_playlist`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `wired_rewards_given`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `wordfilter`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `youtube_playlists`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `catalog_items_limited`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `recycler_prizes`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `crafting_altars_recipes`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `crafting_recipes_ingredients`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `items_hoppers`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `items_presents`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `items_teleports`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `chatlogs_room`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `commandlogs`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `namechange_log`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_enter_log`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `navigator_publics`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_breeds`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_breeding`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_breeding_races`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_commands_data`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_breeding_races`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_commands`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_drinks`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_foods`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_items`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `pet_vocals`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `polls_answers`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_bans`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_game_scores`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_models`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_mutes`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_promotions`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_rights`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_trax`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_trax_playlist`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_votes`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `room_wordfilter`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_achievements`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_achievements_queue`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_clothing`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_currency`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_effects`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_favorite_rooms`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_ignored`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_navigator_settings`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_recipes`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `users_target_offer_purchases`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;

ALTER TABLE `user_window_settings`
ADD COLUMN `id` int NULL DEFAULT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE INDEX `id` (`id`) USING BTREE;
