export enum PetVocalTypeEnum
    {
    DRINKING = 'DRINKING',
    EATING = 'EATING',
    GENERIC_HAPPY = 'GENERIC_HAPPY',
    GENERIC_NEUTRAL = 'GENERIC_NEUTRAL',
    GENERIC_SAD = 'GENERIC_SAD',
    GREET_OWNER = 'GREET_OWNER',
    HUNGRY = 'HUNGRY',
    LEVEL_UP = 'LEVEL_UP',
    MUTED = 'MUTED',
    PLAYFUL = 'PLAYFUL',
    SLEEPING = 'SLEEPING',
    THIRSTY = 'THIRSTY',
    TIRED = 'TIRED',
    UNKNOWN_COMMAND = 'UNKNOWN_COMMAND'
}
